### ISSUE TITLE
Enhance score http client to also return respose headers

### ISSUE THREAD

**Issue by ralucatemle** [CloudSlang/score-actions#109]
Multiple times (expacialy for POST and PUT ) we need the response heders of a HTTP operations.
At this time this are not exposed in th score http client.
An example is the need for the CSRF token.

How to reproduce:
run a GET against a server with CSRF implemented. Observe that from cloudslang you cannot access the response headers while in a HTTP client this is available:
Transfer-Encoding:  chunked
X-Content-Type-Options:  nosniff
X-CSRF-HEADER:  X-CSRF-TOKEN
X-CSRF-PARAM:  _csrf
**X-CSRF-TOKEN:  b9224fa0-f23a-49a3-b7b0-9cced5b62013**
X-XSS-Protection:  1; mode=block

**Comment by mihaitusa** [comment]
The HTTP Client already contains in responseHeader the headers that came from response. So, the actual modification needed is in the HTTP Client Action in base/network/rest content section. The enhancement should also apply to all the lightweight clients.

**Comment by mihaitusa** [comment]
Closed by #592

**Comment by mihaitusa** [comment]
@ralucatemle  See the comments above... is done!
