### ISSUE TITLE
SSH Command works even with corrupted keys (clone of ALM#30586)

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/score-actions#117]
ACTUAL BEHAVIOR: SSH Command works even when the public key has been corrupted: 1 character changed

EXPECTED BEHAVIOR: SSH Command should fail with Auth fail, as it does in Studio

HOW-TO-REPRODUCE: 
1. Change 1st letter of the public key (see an example attached: first A changed to B in .pub file)
2. copy public key on remote linux machine's /root/.ssh folder
3. connect to machine & run  
cd .ssh
touch authorized_keys
chmod 600 authorized_keys
cat ../identity.pub >> authorized_keys
 
4. Run ssh_flow.sl with the inputs:
    - host: *
(host I used)
    - port: "22"
    - username: *
    - password: *
    - command: echo testing
    - pty: "false"
    - privateKeyFile: "C:\\Users\\dumaa\\.ssh\\id_rsa"
(path to private key on your machine)
    - timeout: "90000"
    - characterSet: "UTF-8"
    - closeSession: "false"
    - smart_recovery: "true"
    - retries: 5

! Keys used:
[keys.zip](https://github.com/CloudSlang/score-actions/files/290980/keys.zip)

ENVIRONMENT: (Hardware, OS, OS Version, Browser, etc) 
Ubuntu, cslang-builder #9.58

LINKED ISSUES: ALM#30546

**Comment by gituser173** [comment]
if you add a valid password and an invalid privateKeyFile it should work

**Comment by gituser173** [comment]
if you remove the password altogether and use an invalid privateKeyFile it should not work

**Comment by dumagalex** [comment]
Indeed, it fails with invalid privateKeyFile, as expected, when no password is provided
