### ISSUE TITLE
SSH Command doesn't work with (valid) private key file

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/score-actions#120]
ACTUAL BEHAVIOR: SSH Command fails when specifying a (valid) private key file instead of a password 

EXPECTED BEHAVIOR: SSH Command should work with private key files as well, as it does in OO Studio (CP 1.7.0)

HOW-TO-REPRODUCE: 
1. copy public key on remote linux machine's /root/.ssh folder
2. connect to machine & run
cd .ssh
touch authorized_keys
chmod 600 authorized_keys
cat ../identity.pub >> authorized_keys

3. Run ssh_flow.sl with the inputs:
    - host: {LINUX_HOST}
    - port: "22"
    - username: root
    - command: echo testing
    - privateKeyFile: "LOCAL_PATH\\.ssh\\id_rsa"
    - timeout: "90000"
    - characterSet: "UTF-8"

Keys used:
[validKeys.zip](https://github.com/CloudSlang/score-actions/files/292721/validKeys.zip)

ENVIRONMENT: (Hardware, OS, OS Version, Browser, etc) 
Ubuntu, cslang-builder #9.58

**Comment by gituser173** [comment]
"privateKeyFile" is camel case, it should be snake case: "private_key_file"
