### ISSUE TITLE
need to add tests requirements to CONTRIBUTING.md

### ISSUE THREAD

**Issue by orius123** [CloudSlang/score-actions#21]

**Comment by orius123** [comment]
@Alex-Persa 
do you have any guide lines regarding actions tests?

**Comment by Alex-Persa** [comment]
No, sory. I don't have. Maybe the team who worked on CDP (content development platform) knows more.

**Comment by oritstone** [comment]
@Alex-Persa we include guidelines in our repositories regarding how to contribute new stuff. 
It includes also guidelines regarding how we require this stuff to be tested.
You can look at: https://github.com/CloudSlang/cloud-slang-content/blob/master/CONTRIBUTING.md or https://github.com/CloudSlang/cloud-slang/blob/master/CONTRIBUTING.md for examples

**Comment by Alex-Persa** [comment]
Thanks @oritstone I will look at it.

**Comment by meshipeer** [comment]
closed by #88
