### ISSUE TITLE
SSH service waits 1000 ms between channel polling

### ISSUE THREAD

**Issue by orius123** [CloudSlang/score-actions#72]
Actually 2 issues here:

1. [A constant] (https://github.com/CloudSlang/score-actions/blob/master/score-ssh/src/main/java/io/cloudslang/content/ssh/services/impl/SSHServiceImpl.java#L21) in SSHServiceImpl is configured to 1000 (ms), and is used to define the interval of polling the SSH channel.
2. For some reason the [polling loop] (https://github.com/CloudSlang/score-actions/blob/master/score-ssh/src/main/java/io/cloudslang/content/ssh/services/impl/SSHServiceImpl.java#L132) is a `do .. while` instead of a `while` which means that we wait at least 1 second any way.

this issue has huge impact on cslang flows performance.

@Alex-Persa @meirwah

**Comment by meirwah** [comment]
@lrevnic @Alex-Persa are you aware of this? is this the same for op in OO?

**Comment by Alex-Persa** [comment]
Yes. It's the same for action in OO. 
I agree that the command would be more efficient with a smaller pulling interval. The only reason I can think of for putting 1000 ms is that our input is in seconds. But that doesn't mean that that the command cannot finish faster.
Do you want me to change the do..while in while and to change polling interval value to 100 ms ?

**Comment by meirwah** [comment]
is there a reason they impl it like  that from the first place?
how is it in OO?

**Comment by Alex-Persa** [comment]
The person who implemented this is not in HP anymore so I can't know the reason, maybe because default timeout is 9 secs, usually the input is used as multiple seconds and didn't wanted to do too much checks. 
But I don't see it as a good reason because modest personal computers executes trillions instructions per second. If timeout is set to 1 sec that doesn't mean this can't finish faster.
In OO it's implemented the same way.
This fix wold have a positive performance impact in OO too.

**Comment by meirwah** [comment]
@lrevnic your POV on this?

**Comment by orius123** [comment]
@Alex-Persa I think your suggestion is great! since we are just questioning our own channel and not making  more request, I would even go with less than 100, but I didn't test it much..

**Comment by Alex-Persa** [comment]
@orius123 We can go with less than 100. 
For this I suggest the following solution for an accurate timeout:
"// wait for response
        long currentEpochTime = System.currentTimeMillis();
        long timedOutEpochTime = currentEpochTime + commandTimeout;
        while (!channel.isEOF() && currentEpochTime < timedOutEpochTime) {
            currentEpochTime = System.currentTimeMillis();
            //Thread.sleep(POLLING_INTERVAL); //if needed POLLING_INTERVAL = 1; 
        }
        boolean timedOut = !channel.isEOF() && currentEpochTime > timedOutEpochTime;"

**Comment by orius123** [comment]
LGTM, maybe you can I it the timedout bool before the while loop and use as the loop condition and update it inside the loop. For DRY.

**Comment by bogdan5x** [comment]
I agree with @Alex-Persa's suggestion.
The POLLING_INTERVAL value can be decreased as it affects only the SSHServiceImpl’s thread. The actual SSH command runs on another thread that is managed by jsch library.

**Comment by lrevnic** [comment]
I'm fine with propagating this ER to OO SSH as well.
